.\" vim: filetype=nroff
.TH bf-generate 1 "2014-04-17" "v0.2.0" "bf.zsh"

.SH NAME
bf-generate \- a brainf*ck code generater in bf.zsh.

.SH SYNOPSIS
.B bf generate
.RI < message >...

.SH DESCRIPTION
.B bf-generate
generates a brainf*ck code to print specified message. It is no optimization, so it is too long.

.SH OPTIONS
.TP
.B message
Specified message to print.

.SH BUGS
Please report any bugs to
.IR https://github.com/kagamilove0707/bf.zsh .

.SH LICENSE
Copyright (c) 2014 TSUKIKAGE Osana (MIT License).

.SH SEE ALSO
.BR bf (1)
