.\" vim: filetype=nroff
.TH bf 1 "2014-04-17" "v0.2.1" "bf.zsh"

.SH NAME
bf \- a brainf*ck tools written in pure zsh

.SH SYNOPSIS
.B bf
.I <subcommand>
.RI [ options ...]

.SH DESCRIPTION
.I bf
is a brainf*ck tools written in pure zsh. It is very very slow.

.SH SUBCOMMANDS
.TP
.I run
.BR
Running a brainf*ck code. See also 
.IR bf-run .
.TP
.I generate
Generating a brainf*ck code to print specified message. See also 
.IR bf-generate .

.SH EXAMPLE
.TP
bf run -e "++++[>+<++++]>++."
.TP
bf run input.bf
.TP
bf generate "Hello, World" | bf run -
.TP
bf compress -e "p+r+i+n+t[A>+<++++]>++."

.SH BUGS
Please report any bugs to
.IR https://github.com/kagamilove0707/bf.zsh .

.SH LICENSE
Copyright (c) 2014 TSUKIKAGE Osana (MIT License).

.SH SEE ALSO
.BR bf-run (1),
.BR bf-generate (1)
